"""001 tenant y ledger

Revision ID: a66d1e5f9807
Revises: 
Create Date: 2026-07-10 10:49:48.486445

Recordatorio (doc 04 §6): ninguna migración ejecuta UPDATE/DELETE sobre
`asientos`, `sorteos` ni `auditoria_acciones`; recrear triggers explícitamente
si se tocan esas tablas; toda migración es reversible salvo altas de valores
a CHECKs.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001_tenant_y_ledger'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- Capa 3 (doc 04 §4): triggers de defensa en profundidad, solo MySQL. -----
# Inmutabilidad del ledger y de la auditoría (RN-060, INV-11) + validación
# concepto↔fondo (INV-01..03) a nivel de motor. En SQLite se omiten: la
# inmutabilidad la garantiza el repositorio append-only y las CHECK constraints.
_TRIGGERS_MYSQL_UP = [
    """
    CREATE TRIGGER trg_asientos_no_update BEFORE UPDATE ON asientos
    FOR EACH ROW SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'LEDGER INMUTABLE: UPDATE prohibido (RN-060)'
    """,
    """
    CREATE TRIGGER trg_asientos_no_delete BEFORE DELETE ON asientos
    FOR EACH ROW SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'LEDGER INMUTABLE: DELETE prohibido (RN-060)'
    """,
    """
    CREATE TRIGGER trg_auditoria_no_update BEFORE UPDATE ON auditoria_acciones
    FOR EACH ROW SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'AUDITORIA INMUTABLE: UPDATE prohibido'
    """,
    """
    CREATE TRIGGER trg_auditoria_no_delete BEFORE DELETE ON auditoria_acciones
    FOR EACH ROW SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'AUDITORIA INMUTABLE: DELETE prohibido'
    """,
    # Validación concepto↔fondo (la matriz doc 02 §5 como tercera línea).
    """
    CREATE TRIGGER trg_asientos_valida_concepto_fondo BEFORE INSERT ON asientos
    FOR EACH ROW
    BEGIN
      DECLARE v_tipo VARCHAR(30);
      SELECT tipo INTO v_tipo FROM fondos WHERE id = NEW.fondo_id;
      IF NEW.concepto = 'REVERSION' THEN
        IF NEW.reversa_de_id IS NULL THEN
          SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'REVERSION requiere reversa_de_id (RN-061)';
        END IF;
      ELSEIF NOT (
        (NEW.concepto='CUOTA_AHORRO'              AND v_tipo='AHORRO'       AND NEW.naturaleza='CREDITO') OR
        (NEW.concepto='APORTE_EXTRAORDINARIO'     AND v_tipo='AHORRO'       AND NEW.naturaleza='CREDITO') OR
        (NEW.concepto='DESEMBOLSO_PRESTAMO'       AND v_tipo='AHORRO'       AND NEW.naturaleza='DEBITO')  OR
        (NEW.concepto='RETORNO_CAPITAL'           AND v_tipo='AHORRO'       AND NEW.naturaleza='CREDITO') OR
        (NEW.concepto='INTERES_PAGADO'            AND v_tipo='RENTABILIDAD' AND NEW.naturaleza='CREDITO') OR
        (NEW.concepto='UTILIDAD_ACTIVIDAD'        AND v_tipo='RENTABILIDAD' AND NEW.naturaleza='CREDITO') OR
        (NEW.concepto='PERDIDA_ACTIVIDAD'         AND v_tipo='RENTABILIDAD' AND NEW.naturaleza='DEBITO')  OR
        (NEW.concepto='MULTA_PAGADA'              AND v_tipo='RENTABILIDAD' AND NEW.naturaleza='CREDITO') OR
        (NEW.concepto='DEVOLUCION_AHORRO'         AND v_tipo='AHORRO'       AND NEW.naturaleza='DEBITO')  OR
        (NEW.concepto='DISTRIBUCION_RENTABILIDAD' AND v_tipo='RENTABILIDAD' AND NEW.naturaleza='DEBITO')
      ) THEN
        SIGNAL SQLSTATE '45000'
          SET MESSAGE_TEXT = 'VIOLACION SEPARACION DE FONDOS (INV-01..03)';
      END IF;
    END
    """,
]

_TRIGGERS_MYSQL_DOWN = [
    "DROP TRIGGER IF EXISTS trg_asientos_valida_concepto_fondo",
    "DROP TRIGGER IF EXISTS trg_auditoria_no_delete",
    "DROP TRIGGER IF EXISTS trg_auditoria_no_update",
    "DROP TRIGGER IF EXISTS trg_asientos_no_delete",
    "DROP TRIGGER IF EXISTS trg_asientos_no_update",
]


def _crear_triggers_si_mysql() -> None:
    if op.get_bind().dialect.name == "mysql":
        for ddl in _TRIGGERS_MYSQL_UP:
            op.execute(ddl)


def _eliminar_triggers_si_mysql() -> None:
    if op.get_bind().dialect.name == "mysql":
        for ddl in _TRIGGERS_MYSQL_DOWN:
            op.execute(ddl)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_multas',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo IN ('MORA_CUOTA','MORA_PRESTAMO','MORA_ACTIVIDAD','OTRA')", name='chk_tipo_multa'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_catalogo_multas_natillera_id'), 'catalogo_multas', ['natillera_id'], unique=False)
    op.create_table('configuraciones',
    sa.Column('valor_cuota', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('periodicidad_cuota', sa.String(length=30), nullable=False),
    sa.Column('dia_limite_pago', sa.SmallInteger(), nullable=False),
    sa.Column('permite_aportes_extra', sa.Boolean(), nullable=False),
    sa.Column('tasa_interes_base', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('tasa_interes_min', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('tasa_interes_max', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('max_prestamos_activos', sa.SmallInteger(), nullable=False),
    sa.Column('max_capital_vigente', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estrategia_distribucion', sa.String(length=30), nullable=False),
    sa.Column('estrategia_congelada', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estrategia_distribucion IN ('PARTES_IGUALES','PROPORCIONAL_AHORRO','PROPORCIONAL_TIEMPO')", name='chk_estrategia'),
    sa.CheckConstraint("periodicidad_cuota IN ('MENSUAL','QUINCENAL','SEMANAL')", name='chk_periodicidad'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natillera_id', name='uq_config_natillera'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_configuraciones_natillera_id'), 'configuraciones', ['natillera_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('flag', sa.String(length=50), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natillera_id', 'flag', name='uq_flag_natillera'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_feature_flags_natillera_id'), 'feature_flags', ['natillera_id'], unique=False)
    op.create_table('fondos',
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('saldo_cache', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_cache_actualizado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo IN ('AHORRO','RENTABILIDAD')", name='chk_tipo_fondo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natillera_id', 'tipo', name='uq_fondo_tipo'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_fondos_natillera_id'), 'fondos', ['natillera_id'], unique=False)
    op.create_table('natilleras',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('ciclo_inicio', sa.Date(), nullable=False),
    sa.Column('ciclo_fin', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('BORRADOR','ABIERTA','EN_OPERACION','PENDIENTE_LIQUIDACION','LIQUIDADA','ARCHIVADA')", name='chk_estado_natillera'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('participantes',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo_documento', sa.String(length=4), nullable=False),
    sa.Column('numero_documento', sa.String(length=30), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('ACTIVO','SUSPENDIDO','RETIRADO')", name='chk_estado_participante'),
    sa.CheckConstraint("tipo_documento IN ('CC','CE','TI','PP')", name='chk_tipo_doc'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natillera_id', 'tipo_documento', 'numero_documento', name='uq_participante_doc'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_participantes_natillera_id'), 'participantes', ['natillera_id'], unique=False)
    op.create_table('periodos',
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('mes', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_limite_cuota', sa.Date(), nullable=True),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natillera_id', 'anio', 'mes', name='uq_periodo'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_periodos_natillera_id'), 'periodos', ['natillera_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('asientos',
    sa.Column('fondo_id', sa.BigInteger(), nullable=False),
    sa.Column('participante_id', sa.BigInteger(), nullable=True),
    sa.Column('naturaleza', sa.String(length=10), nullable=False),
    sa.Column('concepto', sa.String(length=40), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('periodo_id', sa.BigInteger(), nullable=True),
    sa.Column('origen_tipo', sa.String(length=30), nullable=False),
    sa.Column('origen_id', sa.BigInteger(), nullable=False),
    sa.Column('reversa_de_id', sa.BigInteger(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('creado_por', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("concepto IN ('CUOTA_AHORRO', 'APORTE_EXTRAORDINARIO', 'DESEMBOLSO_PRESTAMO', 'RETORNO_CAPITAL', 'INTERES_PAGADO', 'UTILIDAD_ACTIVIDAD', 'PERDIDA_ACTIVIDAD', 'MULTA_PAGADA', 'DEVOLUCION_AHORRO', 'DISTRIBUCION_RENTABILIDAD', 'REVERSION')", name='chk_concepto'),
    sa.CheckConstraint("naturaleza IN ('DEBITO', 'CREDITO')", name='chk_naturaleza'),
    sa.CheckConstraint("origen_tipo IN ('CUOTA', 'PRESTAMO', 'PAGO_PRESTAMO', 'ACTIVIDAD', 'MULTA', 'LIQUIDACION', 'REVERSION', 'APORTE_EXTRAORDINARIO')", name='chk_origen_tipo'),
    sa.CheckConstraint('monto > 0', name='chk_monto_positivo'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['fondo_id'], ['fondos.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.ForeignKeyConstraint(['reversa_de_id'], ['asientos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_asientos_natillera_id'), 'asientos', ['natillera_id'], unique=False)
    op.create_table('auditoria_acciones',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=40), nullable=False),
    sa.Column('entidad_id', sa.BigInteger(), nullable=True),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_auditoria_acciones_natillera_id'), 'auditoria_acciones', ['natillera_id'], unique=False)
    op.create_table('configuraciones_historial',
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('autor_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_configuraciones_historial_natillera_id'), 'configuraciones_historial', ['natillera_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('usuarios_natilleras',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('participante_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("rol IN ('ADMINISTRADOR','SUPERVISOR','CLIENTE')", name='chk_rol'),
    sa.ForeignKeyConstraint(['natillera_id'], ['natilleras.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'natillera_id', name='uq_membresia'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_usuarios_natilleras_natillera_id'), 'usuarios_natilleras', ['natillera_id'], unique=False)
    # ### end Alembic commands ###

    # Capa 3: triggers de inmutabilidad y separación de fondos (solo MySQL).
    _crear_triggers_si_mysql()


def downgrade() -> None:
    # Primero los triggers (dependen de las tablas), luego las tablas.
    _eliminar_triggers_si_mysql()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_natilleras_natillera_id'), table_name='usuarios_natilleras')
    op.drop_table('usuarios_natilleras')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_configuraciones_historial_natillera_id'), table_name='configuraciones_historial')
    op.drop_table('configuraciones_historial')
    op.drop_index(op.f('ix_auditoria_acciones_natillera_id'), table_name='auditoria_acciones')
    op.drop_table('auditoria_acciones')
    op.drop_index(op.f('ix_asientos_natillera_id'), table_name='asientos')
    op.drop_table('asientos')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_periodos_natillera_id'), table_name='periodos')
    op.drop_table('periodos')
    op.drop_index(op.f('ix_participantes_natillera_id'), table_name='participantes')
    op.drop_table('participantes')
    op.drop_table('natilleras')
    op.drop_index(op.f('ix_fondos_natillera_id'), table_name='fondos')
    op.drop_table('fondos')
    op.drop_index(op.f('ix_feature_flags_natillera_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_configuraciones_natillera_id'), table_name='configuraciones')
    op.drop_table('configuraciones')
    op.drop_index(op.f('ix_catalogo_multas_natillera_id'), table_name='catalogo_multas')
    op.drop_table('catalogo_multas')
    # ### end Alembic commands ###
