"""002 cuotas e idempotencia

Revision ID: e56e91ca8bbd
Revises: 0001_tenant_y_ledger
Create Date: 2026-07-10 14:22:07.760796

Recordatorio (doc 04 §6): ninguna migración ejecuta UPDATE/DELETE sobre
`asientos`, `sorteos` ni `auditoria_acciones`; recrear triggers explícitamente
si se tocan esas tablas; toda migración es reversible salvo altas de valores
a CHECKs.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002_cuotas_e_idempotencia'
down_revision: str | None = '0001_tenant_y_ledger'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('clave', sa.String(length=64), nullable=False),
    sa.Column('hash_payload', sa.String(length=64), nullable=False),
    sa.Column('referencia_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natillera_id', 'clave', name='uq_idempotency'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_idempotency_keys_natillera_id'), 'idempotency_keys', ['natillera_id'], unique=False)
    op.create_table('cuotas',
    sa.Column('participante_id', sa.BigInteger(), nullable=False),
    sa.Column('periodo_id', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('pagada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asiento_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('PENDIENTE','PAGADA','REVERTIDA')", name='chk_estado_cuota'),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natillera_id', 'participante_id', 'periodo_id', name='uq_cuota_periodo'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_cuotas_natillera_id'), 'cuotas', ['natillera_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cuotas_natillera_id'), table_name='cuotas')
    op.drop_table('cuotas')
    op.drop_index(op.f('ix_idempotency_keys_natillera_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
