"""003 prestamos y multas

Revision ID: 64f2f172e353
Revises: 0002_cuotas_e_idempotencia
Create Date: 2026-07-10 15:45:32.784198

Recordatorio (doc 04 §6): ninguna migración ejecuta UPDATE/DELETE sobre
`asientos`, `sorteos` ni `auditoria_acciones`; recrear triggers explícitamente
si se tocan esas tablas; toda migración es reversible salvo altas de valores
a CHECKs.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0003_prestamos_y_multas'
down_revision: str | None = '0002_cuotas_e_idempotencia'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prestamos',
    sa.Column('participante_id', sa.BigInteger(), nullable=False),
    sa.Column('capital', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tasa_interes', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('plazo_meses', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_desembolso', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('motivo_rechazo', sa.String(length=255), nullable=True),
    sa.Column('saldo_capital', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('SOLICITADO','APROBADO','RECHAZADO','DESEMBOLSADO','EN_PAGO','EN_MORA','PAGADO')", name='chk_estado_prestamo'),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_prestamos_natillera_id'), 'prestamos', ['natillera_id'], unique=False)
    op.create_index(op.f('ix_prestamos_participante_id'), 'prestamos', ['participante_id'], unique=False)
    op.create_table('multas',
    sa.Column('participante_id', sa.BigInteger(), nullable=False),
    sa.Column('catalogo_multa_id', sa.BigInteger(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('origen_tipo', sa.String(length=30), nullable=True),
    sa.Column('origen_id', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('pagada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asiento_id', sa.BigInteger(), nullable=True),
    sa.Column('anulada_por', sa.BigInteger(), nullable=True),
    sa.Column('justificacion_anulacion', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('IMPUESTA','PAGADA','ANULADA')", name='chk_estado_multa'),
    sa.ForeignKeyConstraint(['anulada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos.id'], ),
    sa.ForeignKeyConstraint(['catalogo_multa_id'], ['catalogo_multas.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_multas_natillera_id'), 'multas', ['natillera_id'], unique=False)
    op.create_index(op.f('ix_multas_participante_id'), 'multas', ['participante_id'], unique=False)
    op.create_table('prestamo_pagos',
    sa.Column('prestamo_id', sa.BigInteger(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto_recibido', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('componente_capital', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('componente_interes', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('asiento_capital_id', sa.BigInteger(), nullable=True),
    sa.Column('asiento_interes_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('componente_capital + componente_interes = monto_recibido', name='chk_descomposicion'),
    sa.ForeignKeyConstraint(['asiento_capital_id'], ['asientos.id'], ),
    sa.ForeignKeyConstraint(['asiento_interes_id'], ['asientos.id'], ),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_prestamo_pagos_natillera_id'), 'prestamo_pagos', ['natillera_id'], unique=False)
    op.create_index(op.f('ix_prestamo_pagos_prestamo_id'), 'prestamo_pagos', ['prestamo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prestamo_pagos_prestamo_id'), table_name='prestamo_pagos')
    op.drop_index(op.f('ix_prestamo_pagos_natillera_id'), table_name='prestamo_pagos')
    op.drop_table('prestamo_pagos')
    op.drop_index(op.f('ix_multas_participante_id'), table_name='multas')
    op.drop_index(op.f('ix_multas_natillera_id'), table_name='multas')
    op.drop_table('multas')
    op.drop_index(op.f('ix_prestamos_participante_id'), table_name='prestamos')
    op.drop_index(op.f('ix_prestamos_natillera_id'), table_name='prestamos')
    op.drop_table('prestamos')
    # ### end Alembic commands ###
