"""004 actividades

Revision ID: 41fdf0562e6e
Revises: 0003_prestamos_y_multas
Create Date: 2026-07-10 17:27:11.590355

Recordatorio (doc 04 §6): ninguna migración ejecuta UPDATE/DELETE sobre
`asientos`, `sorteos` ni `auditoria_acciones`; recrear triggers explícitamente
si se tocan esas tablas; toda migración es reversible salvo altas de valores
a CHECKs.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0004_actividades'
down_revision: str | None = '0003_prestamos_y_multas'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Inmutabilidad de `sorteos` (RF-505), solo MySQL (como el ledger, doc 04 §4).
_TRG_UP = [
    """
    CREATE TRIGGER trg_sorteos_no_update BEFORE UPDATE ON sorteos
    FOR EACH ROW SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'SORTEO INMUTABLE: UPDATE prohibido (RF-505)'
    """,
    """
    CREATE TRIGGER trg_sorteos_no_delete BEFORE DELETE ON sorteos
    FOR EACH ROW SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'SORTEO INMUTABLE: DELETE prohibido (RF-505)'
    """,
]
_TRG_DOWN = [
    "DROP TRIGGER IF EXISTS trg_sorteos_no_delete",
    "DROP TRIGGER IF EXISTS trg_sorteos_no_update",
]


def _triggers_up() -> None:
    if op.get_bind().dialect.name == "mysql":
        for ddl in _TRG_UP:
            op.execute(ddl)


def _triggers_down() -> None:
    if op.get_bind().dialect.name == "mysql":
        for ddl in _TRG_DOWN:
            op.execute(ddl)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('periodo_id', sa.BigInteger(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('valor_numero', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cantidad_numeros', sa.SmallInteger(), nullable=True),
    sa.Column('premio', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fecha_sorteo', sa.Date(), nullable=True),
    sa.Column('clonada_de_id', sa.BigInteger(), nullable=True),
    sa.Column('utilidad_cierre', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('BORRADOR','ABIERTA','SORTEADA','CERRADA')", name='chk_estado_actividad'),
    sa.CheckConstraint("tipo IN ('POLLA','RIFA','BINGO','BAZAR','VENTA','OTRO','DONACION')", name='chk_tipo_actividad'),
    sa.ForeignKeyConstraint(['clonada_de_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_actividades_natillera_id'), 'actividades', ['natillera_id'], unique=False)
    op.create_table('actividad_movimientos',
    sa.Column('actividad_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('concepto', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('participante_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo IN ('INGRESO','GASTO','PREMIO')", name='chk_tipo_movimiento'),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_actividad_movimientos_actividad_id'), 'actividad_movimientos', ['actividad_id'], unique=False)
    op.create_index(op.f('ix_actividad_movimientos_natillera_id'), 'actividad_movimientos', ['natillera_id'], unique=False)
    op.create_table('actividad_numeros',
    sa.Column('actividad_id', sa.BigInteger(), nullable=False),
    sa.Column('numero', sa.SmallInteger(), nullable=False),
    sa.Column('participante_id', sa.BigInteger(), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.Column('pagado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actividad_id', 'numero', name='uq_actividad_numero'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_actividad_numeros_actividad_id'), 'actividad_numeros', ['actividad_id'], unique=False)
    op.create_index(op.f('ix_actividad_numeros_natillera_id'), 'actividad_numeros', ['natillera_id'], unique=False)
    op.create_table('sorteos',
    sa.Column('actividad_id', sa.BigInteger(), nullable=False),
    sa.Column('numero_ganador', sa.SmallInteger(), nullable=False),
    sa.Column('hubo_ganador', sa.Boolean(), nullable=False),
    sa.Column('participante_ganador_id', sa.BigInteger(), nullable=True),
    sa.Column('fuente', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['participante_ganador_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actividad_id', name='uq_sorteo_actividad'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_sorteos_natillera_id'), 'sorteos', ['natillera_id'], unique=False)
    # ### end Alembic commands ###
    _triggers_up()  # inmutabilidad de sorteos (solo MySQL)


def downgrade() -> None:
    _triggers_down()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sorteos_natillera_id'), table_name='sorteos')
    op.drop_table('sorteos')
    op.drop_index(op.f('ix_actividad_numeros_natillera_id'), table_name='actividad_numeros')
    op.drop_index(op.f('ix_actividad_numeros_actividad_id'), table_name='actividad_numeros')
    op.drop_table('actividad_numeros')
    op.drop_index(op.f('ix_actividad_movimientos_natillera_id'), table_name='actividad_movimientos')
    op.drop_index(op.f('ix_actividad_movimientos_actividad_id'), table_name='actividad_movimientos')
    op.drop_table('actividad_movimientos')
    op.drop_index(op.f('ix_actividades_natillera_id'), table_name='actividades')
    op.drop_table('actividades')
    # ### end Alembic commands ###
