"""005 liquidacion

Revision ID: 27072f68b973
Revises: 0004_actividades
Create Date: 2026-07-10 21:00:14.361387

Recordatorio (doc 04 §6): ninguna migración ejecuta UPDATE/DELETE sobre
`asientos`, `sorteos` ni `auditoria_acciones`; recrear triggers explícitamente
si se tocan esas tablas; toda migración es reversible salvo altas de valores
a CHECKs.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0005_liquidacion'
down_revision: str | None = '0004_actividades'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidaciones',
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('estrategia_aplicada', sa.String(length=30), nullable=True),
    sa.Column('saldo_rentabilidad_distribuido', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('confirmada_por', sa.BigInteger(), nullable=True),
    sa.Column('confirmada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('PRE_VALIDACION','CALCULADA','EN_REVISION','CONFIRMADA','ACTA_GENERADA')", name='chk_fase_liquidacion'),
    sa.ForeignKeyConstraint(['confirmada_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natillera_id', name='uq_liquidacion_natillera'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_liquidaciones_natillera_id'), 'liquidaciones', ['natillera_id'], unique=False)
    op.create_table('liquidacion_decisiones',
    sa.Column('liquidacion_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_bloqueo', sa.String(length=40), nullable=False),
    sa.Column('origen_tipo', sa.String(length=30), nullable=False),
    sa.Column('origen_id', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.String(length=255), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('decidido_por', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['decidido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_liquidacion_decisiones_liquidacion_id'), 'liquidacion_decisiones', ['liquidacion_id'], unique=False)
    op.create_index(op.f('ix_liquidacion_decisiones_natillera_id'), 'liquidacion_decisiones', ['natillera_id'], unique=False)
    op.create_table('liquidacion_detalles',
    sa.Column('liquidacion_id', sa.BigInteger(), nullable=False),
    sa.Column('participante_id', sa.BigInteger(), nullable=False),
    sa.Column('ahorros', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('participacion_rentabilidad', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('capital_pendiente', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('intereses_pendientes', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('multas_pendientes', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=False),
    sa.Column('entregado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entregado_por', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('natillera_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('saldo_final = ahorros + participacion_rentabilidad - capital_pendiente - intereses_pendientes - multas_pendientes', name='chk_saldo_final'),
    sa.ForeignKeyConstraint(['entregado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_liquidacion_detalles_liquidacion_id'), 'liquidacion_detalles', ['liquidacion_id'], unique=False)
    op.create_index(op.f('ix_liquidacion_detalles_natillera_id'), 'liquidacion_detalles', ['natillera_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liquidacion_detalles_natillera_id'), table_name='liquidacion_detalles')
    op.drop_index(op.f('ix_liquidacion_detalles_liquidacion_id'), table_name='liquidacion_detalles')
    op.drop_table('liquidacion_detalles')
    op.drop_index(op.f('ix_liquidacion_decisiones_natillera_id'), table_name='liquidacion_decisiones')
    op.drop_index(op.f('ix_liquidacion_decisiones_liquidacion_id'), table_name='liquidacion_decisiones')
    op.drop_table('liquidacion_decisiones')
    op.drop_index(op.f('ix_liquidaciones_natillera_id'), table_name='liquidaciones')
    op.drop_table('liquidaciones')
    # ### end Alembic commands ###
